### ISSUE TITLE
Navigation to problem location with double click is not working in IntelliJ 2020.3

### ISSUE THREAD

**Issue by rspence19** [Daimler/sechub-plugin-intellij#13]
The line, column and location of the problem are being displayed in the table at the left side but double clicking does not open the affected source code.

**Comment by Jeeppler** [comment]
@rspence19 thank you for reporting the issue.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Hello @rspence19 , could it be that your machine is a windows machine and the pathes inside your report are linux styled? 

At the moment I am developing the VSCode/VSCodium/Eclipse Theia plugin and inspecting the `FileLocationExplorer.java` . I am not sure but this could be the problem.

**Comment by rspence19** [comment]
> Hello @rspence19 , is your developer machine a Windows client and the pathes inside your report Unix styled? (\ vs. /)
> 
> At the moment I am developing the VSCode/VSCodium/Eclipse Theia plugin and inspecting the `FileLocationExplorer.java` . I am not sure but this could be the problem.

Hi, @de-jcup , yes, it is correct. I am using a windows client and the pathes are unix like.

**Comment by company-jcup** [comment]
Tried out with 
- Windows 10
- IntelliJ 2020-03
- Java 15
- Test sechub report
- origin sechub report standard gradle structure

![image](https://user-images.githubusercontent.com/80676663/113172120-6b464500-9248-11eb-849b-59891ca2e057.png)

So same problem. Sounds more and more like a windows path problem.

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
