### ISSUE TITLE
Show CWE-Ids within Plugin

### ISSUE THREAD

**Issue by 4w31ss3** [Daimler/sechub-plugin-intellij#6]
At the moment the plugin isn't displaying the CWE-Id from the sechub json report.

It would be great if this information would be added as a column with in the findings table.

---
<sup>Albert Weißert <albert.weissert@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
We will handle this the same way as doine for eclipse plugin in https://github.com/Daimler/sechub-plugin-eclipse/issues/3, so we show up a CWE-Link next finding name.

**Comment by de-jcup** [comment]
Implementation now as shown in next picture: 
![image](https://user-images.githubusercontent.com/11644753/101966660-dc6dd800-3c18-11eb-9764-cbf2698e0ebe.png)

Will open dedicated mitre description website - upper example opens:
![image](https://user-images.githubusercontent.com/11644753/101966975-22776b80-3c1a-11eb-8926-f46d1a68d116.png)
